import {auth} from '@/auth';
import SiteHeader from '@/components/site-header';
import Providers from '@/config/providers';
import * as api from '@/lib/api';
import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import {Toaster} from 'sonner';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [session, profile, categories] = await Promise.all([auth(), api.getProfile(), api.getAllCategories()]);

  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <SiteHeader session={session} profile={profile.data} categories={categories.data || []} />
          {children}
        </Providers>
        <Toaster position='bottom-center' />
      </body>
    </html>
  );
}
